//size(300, 400);
fullScreen();
color black=#000000, white=#FFFFFF, yellow=#F8FC03, purple=#980AFF, yellowNight=#F8FC00, purpleNight=#CA259B;
float x=displayWidth*1/4, y=displayHeight*1/4, widthRect=displayWidth*1/2;
float heightRect=displayHeight*1/2;
int thin=width*1/50, thick=2*thin;
background(black);
stroke(yellowNight);
fill(purpleNight);
rect(x, y, widthRect, heightRect);
